FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy application
COPY . .

# Build
RUN npm run build

# Production
FROM node:20-alpine
WORKDIR /app
COPY --from=0 /app/.next ./.next
COPY --from=0 /app/public ./public
COPY --from=0 /app/package*.json ./
RUN npm install --production

EXPOSE 3000
CMD ["npm", "start"]
